# docker-compose.yml

version: '3'

services:
  external:
    container_name: debtsnap
    # The name of the image that will be created when building this container
    image: debtsnap:latest
    build:
      context: .
      dockerfile: Dockerfile
    user: 'node'
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      - NODE_ENV=production

      - PRIVATE_VAPID_KEY=${PRIVATE_VAPID_KEY}
      - PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY}
      - SECRET_EMAIL=${SECRET_EMAIL}
      - SECRET_PASSWORD=${SECRET_PASSWORD}

    restart: unless-stopped
    ports:
      - 3000:5050
